export {Home} from "./Home/Home"
export {Register} from "./Register/Register"
export {Login} from "./Login/Login"
export {DirectorDetail} from "./DirectorDetail/DirectorDetail"
export {MovieDetail} from "./MovieDetail/MovieDetail"
export {EditProfile} from "./EditProfile/EditProfile"